name: bilgi_kutusu_oua_appjam
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.3
  html: ^0.15.0

  #STATE_MANAGEMENT
  stacked: ^3.4.2
  stacked_services: ^1.5.0

  #UI
  flutter_platform_widgets: ^6.1.0
  font_awesome_flutter: ^10.7.0

  #DI
  get_it:
    ^7.7.0

    #API
  dio: ^5.4.3+1
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  stacked_generator: ^1.6.0
  retrofit_generator: ">=7.0.0 <8.0.0"
  build_runner: ">=2.3.0 <4.0.0"

flutter:
  assets:
    - assets/resimler/kultur.jpg
    - assets/resimler/egitim.jpg
    - assets/resimler/saglık.jpeg
    - assets/resimler/hobi.jpg
    - assets/resimler/teknoloji.jpg
    - assets/resimler/bilgi.jpg
    - assets/resimler/çiçek.png
